name: admin_team_boke
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 路由
  auto_route: ^3.2.0
  # 状态管理
  flutter_hooks: 0.18.1
  hooks_riverpod: 1.0.2
  # 弹窗
  flutter_easyloading: ^3.0.3

  # 数据解析
  freezed_annotation:
  json_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: 3.1.0
  build_runner:
  freezed:
  json_serializable:
  flutter_gen_runner:

# 资源配置
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)
  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true
  #    rive: true
  assets:
    enabled: true
    package_parameter_enabled: false
    # Assets.imagesChip
    # style: camel-case

    # Assets.images_chip
    # style: snake-case

    # Assets.images.chip (default style)
    # style: dot-delimiter
  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

# 国际化
flutter_intl:
  enabled: true